from dataclasses import dataclass

@dataclass
class SidecarConfig:
    symbols: list[str]
    thresholds: list[int]
    include_microstructure: bool = ...
    gap_fill_on_startup: bool = ...
    verbose: bool = ...
    timeout_ms: int = ...

    @classmethod
    def from_env(cls) -> SidecarConfig: ...

def run_sidecar(config: SidecarConfig) -> None: ...
